var AxShadingOperation = Object.freeze(
{
    None : 0,
    BasicShading : 1,
    FlatColor : 2,
    Tint : 3,
    AmbientLighting : 4,
    LightSource : 5,
    VertexLighting : 6,
    PixelLighting : 7,
    ColorMap : 8,
    ReflectionMap : 9,
    RefractionMap : 10,
    NormalMap : 11,
    BlurMap : 12,
    HBlur : 13,
    VBlur : 14,
    AlignScreenQuad : 15,
    ProjectTexture : 16,
    ProjectPicture : 17,
    ShadowMapWriter : 18,
    ShadowMap : 19,
    TextureTransform : 20,
    Skinning : 21,
    Material : 22,
    Fog : 23,
    BumpMap : 24,
    ChangeCulling : 25
});